version: "3.7"

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-echo-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./init/:/docker-entrypoint-initdb.d:rw
      - app_db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


volumes:
  app_db:


networks:
  nt_mysql:
    driver: bridge
